### ISSUE TITLE
New Device from existing one as "symbolic link" - Idea

### ISSUE THREAD

**Issue by Melwindp** [sbormann/ioBroker.iqontrol#140]
Hi iqontrol Team,

maybe it would be a great idea, that we can add an existing device to a view without copying. like a symbolic link / verknüpfung. so you can use one device at different views and a change of a device has impact to all.

Great work, im using the adapter since a week.

Melwin

**Comment by sbormann** [comment]
Hi, great Idea, i will think about how to implement that! Greetings, Sebastian

--
Von meinem iPhone aus gesendet

Am 27.08.2020 um 18:11 schrieb Melwindp <notifications@github.com>:

﻿

Hi iqontrol Team,

maybe it would be a great idea, that we can add an existing device to a view without copying. like a symbolic link / verknüpfung. so you can use one device at different views and a change of a device has impact to all.

Great work, im using the adapter since a week.

Melwin

**Comment by Melwindp** [comment]
thanks for the quick answer and maybe I can help somehow in the future.

**Comment by sbormann** [comment]
Hi, das geht jetzt mit der aktuellen Github-Version.
