### ISSUE TITLE
RGB Farbe nicht auswählbar

### ISSUE THREAD

**Issue by maxtry** [sbormann/ioBroker.iqontrol#153]
**Describe the bug**  
Bei der Einrichtung meines Osram LED Streifens, habe ich bemerkt, dass die RGB Farben beim frischen öffnen der iQontrol Oberfläche + wenn das Gerät auf der Startansicht (Home) platziert ist, nicht auswählbar sind. Erst wenn ich z.B. auf eine andere Ansicht wechseln tue und anschließend wieder zurück zur Startansicht, dann kann ich erst die Farben auswählen. 
Wenn ich das Geräte z.B. auf einer anderen Ansicht platziere, kann ich problemlos direkt die Farben auswählen. 

**To Reproduce**  
1. iQontrol öffnen -> auf der Startansicht, Farbe nicht auswählbar
2. Ansicht wechseln und anschließend wieder zur Startansicht -> Farbe auswählbar

Beim frischen Öffnen vom iQontrol Farbe nicht auswählbar
![Startansicht](https://user-images.githubusercontent.com/52544096/99607063-4f65a380-2a0b-11eb-9fe4-8e96ebd6490c.png)

Nach dem Wechseln zur einer anderen Ansicht und anschließend wieder zurück zur Startansicht, Farbe auswählbar.
![nach dem wechsel](https://user-images.githubusercontent.com/52544096/99607155-8045d880-2a0b-11eb-9627-fec32856a256.png)

 
**Versions:**  
 - Adapter version: 1.4.1
 - JS-Controller version: 3.1.6
 - Node version: v12.19.0
 - Operating system: <Debian Buster>

**Comment by L0rz** [comment]
Habe den Gleich Fehler:
immer Wenn für ein Objekt nur der ALTERNATIVE_COLORSPACE_VALUE angegeben ist

**Comment by sbormann** [comment]
...oh mann, eine neverending story. Ich hatte gehofft, mit der 1.3.4 jetzt endlich die Probleme gelöst zu haben.
Bitte schickt mal Log-Auszüge von der Entwicklerkonsole, einmal wenn es nicht geht, und einmal wenn es dann beim zweiten Aufruf doch geht:

https://github.com/sbormann/ioBroker.iqontrol#troubleshooting

Ach ja, vielleicht probiert doch auch erst noch mal die aktuelle Github-Version von iQontrol. Ich glaube zwar, dass ich da nichts mehr diesbezüglich geändert hatte - allerdings kann ich mich auch nicht mehr an alle Änderungen im einzelnen erinnern. Ein bisschen Hoffnung habe ich noch, dass es mit der aktuellen Version geht... :)

**Comment by DcFamas** [comment]
Moin @sbormann das Problem besteht bei mir auch.

Aktueller Status:
Adapter version: 1.5.5
JS-Controller version: 3.1.6
node version: v12.20.1
operating system: proxmox -> debian -> iobroker

Was verwunderlich ist ist, dass die rgb Leiste beim Start des Systems (& ich meine manchmal) angezeigt wird. Wenn ioBroker & damit iQontrol vollständig geladen ist verschwindet der rgb Slider dann.

Ich kenne mich mit Debuggin/HTTP leider gar nicht aus, deswegen hier mein Vorgang:

öffnen von der Ansicht, Debuggin/Console öffnen und dann Klick auf "Hängelampen" im "Schlafzimmer":

`viewDeviceContextMenu start via TOUCHSTART/MOUSEDOWN index.js:7795:11
viewDeviceContextMenu start function index.js:7818:10
toolbarContextMenu end function index.js:5101:10
toolbarContextMenu end function - find active Toolbar Index index.js:5106:11
viewDeviceContextMenu level: -0.18750000000000003 index.js:7840:12
viewDeviceContextMenu level: -0.125 index.js:7840:12
viewDeviceContextMenu level: -0.062499999999999986 index.js:7840:12
viewDeviceContextMenu ignore click ended after 100ms index.js:7827:11
viewDeviceContextMenu level: 0 index.js:7840:12
toolbarContextMenu end via TOUCHEND/MOUSEUP index.js:5051:11
toolbarContextMenu end function index.js:5101:10
viewDeviceContextMenu end via TOUCHEND/MOUSEUP index.js:7806:11
viewDeviceContextMenu end function index.js:7858:10
viewDeviceContextMenu end via TOUCHEND/MOUSEUP index.js:7806:11
viewDeviceContextMenu end function index.js:7858:10
viewDeviceContextMenu device CLICK index.js:7779:11
viewDeviceContextMenu end function index.js:7858:10
renderDialog iqontrol.0.Views.Schlafzimmer.devices.0 index.js:7913:10
Array []
index.js:7945:12
Add timestamp to Hängelampen with value 0 2 index.js:7582:10
Converting #RGB from #ffe896 to H|S|B/CT|B... index.js:4210:10
...result is 47|41|100/null|null index.js:4313:10
Converting H|S|B/CT|B from 47|41|100/25|null to #RGB... index.js:4159:10
...result is #ffe896 index.js:4201:10
>>>>>> setState scene.0.Schlafzimmer-Scene_rgb: #ffe896 --> #ffe896 index.js:3423:11
[Socket] setState scene.0.Schlafzimmer-Scene_rgb --> val: #ffe896 index.js:2824:10
Converting #RGB from #ffe896 to H|S|B/CT|B... index.js:4210:10
...result is 47|41|100/null|null index.js:4313:10
Converting H|S|B/CT|B from 47|41|100/25|null to #RGB... index.js:4159:10
...result is #ffe896 index.js:4201:10
Not sending state, because a white value was changed, but AlternativeColorspace is without white index.js:5962:24
>> ack: true val: #ffe896 newVal: #ffe896 index.js:3641:11
<< ack-val reached new val: preventUpdate regular ended. index.js:3644:11
Converting #RGB from #ffe896 to H|S|B/CT|B... index.js:4210:10
...result is 47|41|100/null|null index.js:4313:10
toolbarContextMenu end function - find active Toolbar Index index.js:5106:11
deliverState done index.js:2827:11
Converting #RGB from #ffe896 to H|S|B/CT|B... index.js:4210:10
...result is 47|41|100/null|null index.js:4313:10
Converting #RGB from #ffe896 to H|S|B/CT|B... index.js:4210:10
...result is 47|41|100/null|null index.js:4313:10
toolbarContextMenu end function - end ignoreStart index.js:5120:11
Converting #RGB from #ffe896 to H|S|B/CT|B... index.js:4210:10
...result is 47|41|100/null|null index.js:4313:10
Converting #RGB from #ffe896 to H|S|B/CT|B... index.js:4210:10
...result is 47|41|100/null|null index.js:4313:10
toolbarContextMenu end function - end ignoreStart index.js:5120:11
Converting #RGB from #ffe896 to H|S|B/CT|B... index.js:4210:10
...result is 47|41|100/null|null index.js:4313:10
viewDeviceContextMenu end function - end ignoreStart 3 index.js:7863:11
viewTimestampElapsedTimer for 0 states index.js:7390:12
viewTimestampElapsedTimer for 0 states`

**Comment by sbormann** [comment]
Hi,
bitte mal mit der aktuellen Github-Version testen. Ich hoffe, es geht jetzt!
Bitte um Rückmeldung.
VG!

**Comment by DcFamas** [comment]
Ich bin zu dumm die "dev" Version zu installieren.
Über die Katze in ioBroker bekomme ich nur die 1.5.5 und selbst über den Link und die Katze
https://github.com/sbormann/ioBroker.iqontrol

nur die 1.5.5 wie kann ich die 1.5.6.dev installieren?

Danke für deine schnelle Hifle! :)

**Comment by sbormann** [comment]
Die Github-Version hat keine eigene Versionsnummer, die bleibt auf 1.5.5 stehen.

**Comment by DcFamas** [comment]
Problem ist bei mir behoben mit der neuen Version! :)
Vielen Dank dafür!

**Comment by DcFamas** [comment]
Moin @sbormann,
mir ist nun noch aufgefallen, dass jedes Mal wenn man auf die Ansicht geht in der der die alternative Farbe genutzt wird der Ladebalken des Gerätes sehr lange angezeigt wird:

![grafik](https://user-images.githubusercontent.com/35306967/105577514-74afbe80-5d7a-11eb-9bfe-671614f54e90.png)

Das stört mich persönlich nicht sonderlich, möchte es nur anmerken. Der Status ist ca. für fünf Sekunden so.

`Fetched Object: zigbee.0.00158d0004a01914.available index.js:2786:13
>> ack: false val: #ff7b00 newVal: #ff7b00 index.js:3641:11
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null index.js:4324:10
"K": {"en": "K", "de": "K", "ru": "K", "pt": "K", "nl": "K", "fr": "K"}, translate.js:24:17
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null index.js:4324:10
"K": {"en": "K", "de": "K", "ru": "K", "pt": "K", "nl": "K", "fr": "K"}, translate.js:24:17
Converting H|S|B/CT|B from 29|100|100/0|null to #RGB... index.js:4159:10
...result is #ff7b00 index.js:4206:10
Not sending state, because a white value was changed, but AlternativeColorspace is without white index.js:6024:24
Fetch object: index.js:2779:11
[Socket] getObject index.js:2780:11
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null index.js:4324:10
"K": {"en": "K", "de": "K", "ru": "K", "pt": "K", "nl": "K", "fr": "K"}, translate.js:24:17
Converting H|S|B/CT|B from 29|100|100/0|null to #RGB... index.js:4159:10
...result is #ff7b00 index.js:4206:10
>>>>>> setState yeelight-2.0.Schlafzimmer-Decke.control.rgb: #ff7b00 --> #ff7b00 index.js:3423:11
[Socket] setState yeelight-2.0.Schlafzimmer-Decke.control.rgb --> val: #ff7b00 index.js:2824:10
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null index.js:4324:10
"K": {"en": "K", "de": "K", "ru": "K", "pt": "K", "nl": "K", "fr": "K"}, translate.js:24:17
Converting H|S|B/CT|B from 29|100|100/0|null to #RGB... index.js:4159:10
...result is #ff7b00 index.js:4206:10
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null index.js:4324:10
"K": {"en": "K", "de": "K", "ru": "K", "pt": "K", "nl": "K", "fr": "K"}, translate.js:24:17
Converting H|S|B/CT|B from 29|100|100/0|null to #RGB... index.js:4159:10
...result is #ff7b00 index.js:4206:10
Shuffle! index.js:12035:162
>> ack: false val: #ff7b00 newVal: #ff7b00 index.js:3641:11
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null index.js:4324:10
Shuffle! index.js:12034:162
>> ack: false val: #ff7b00 newVal: #ff7b00 index.js:3641:11
>> ack: false val: #ff7b00 newVal: #ff7b00 index.js:3641:11
deliverState done index.js:2827:11
Fetched Object: hm-rpc.0.PEQ1316457.4.VALVE_STATE index.js:2786:13
Add timestamp to Heizung with value 17°C<span class='small'>&nbsp;Automatik</span> index.js:7644:10
Object not found index.js:2796:13
deliverState done index.js:2827:11
>> ack: false val: #ff7b00 newVal: #ff7b00 index.js:3641:11
>> ack: false val: #ff7b00 newVal: #ff7b00 index.js:3641:11
>> ack: false val: #ff7b00 newVal: #ff7b00 index.js:3641:11
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null index.js:4324:10
>> ack: false val: #ff7b00 newVal: #ff7b00 index.js:3641:11
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null index.js:4324:10
Shuffle! index.js:12035:162
<< preventUpdate dexpired. index.js:3519:13
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null index.js:4324:10
<< preventUpdate dexpired. index.js:3519:13
Converting #RGB from #ff7b00 to H|S|B/CT|B... index.js:4215:10
...result is 29|100|100/null|null`
