### ISSUE TITLE
2 instances but only one link

### ISSUE THREAD

**Issue by ldittmar81** [sbormann/ioBroker.iqontrol#22]
Hi. I have 2 instances of iqontrol. One for me and one for my wife, but I can see only one link on tab and on web.

![07-05-_2019_09-11-24](https://user-images.githubusercontent.com/9552828/57280415-62bf5100-70a9-11e9-8efb-5b0dcd9d401b.jpg)

![07-05-_2019_09-13-06](https://user-images.githubusercontent.com/9552828/57280465-65ba4180-70a9-11e9-8f3c-7feeb11e6ec9.jpg)

---

**System data:**

Model: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM: 7.65 GB
Node.js: v8.15.1
NPM: 6.4.1
Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
JS-Controller (1): 1.5.7
Admin: 3.6.2
iQontrol: 0.0.15

> *created by ioBroker.info*

**Comment by sbormann** [comment]
I made it this way, because i think it fits to most users, to have only one instance inside iobroker.
But you can save links to different instances in your browser-favorites or as web-app on your phone.

Inside web-adapter i don't know how to add more links - i think here it would make sense, to add each instance. Do you know how to do it?

syntax is:
http://<ip>:8082/iqontrol/index.html?namespace=iqontrol.0 for instance 0,
http://<ip>:8082/iqontrol/index.html?namespace=iqontrol.1 for instance 1 and so on.

![image](https://user-images.githubusercontent.com/49171332/57318492-c160eb00-70fa-11e9-83ef-c8593daac200.png)

**Comment by sbormann** [comment]
Hi, as i have no clue how to offer a solution, i would like to close this issue for now. If anyone has a hint or further questrions feel free to reopen this issue.
