### ISSUE TITLE
Datapoint as URL

### ISSUE THREAD

**Issue by Esto88** [sbormann/ioBroker.iqontrol#272]
**Describe the bug**  
When the Value in the Datapont has only for Example an IP Adress. 
IQontrol adds:
**http://"IP-AdressControler"/iqontrol/** and then The Value from the Datapoint
When the Value in the Datapoint already has an "http://" IQontrol does nothing.

Is this behavior intended?

Option in HTML/URL
-Open URL in New Window
Version of IQontrol: 
V2.1.0

**Comment by sbormann** [comment]
Hi, this is the default behaviour how urls are referenced in html.
An ip-adress without protocol ("http://") is equal to any other string and therefore a reference inside the actual directory the calling page is.
The reason you might find that unintuitive is, that modern browsers automatically hide (but internally add) the https:// to any url you enter in the search bar. But doing that is no option, because that would take the possibility to reference to diretorys inside the page.
