### ISSUE TITLE
RGB Steuerung geplant?

### ISSUE THREAD

**Issue by ihavenonick** [sbormann/ioBroker.iqontrol#53]
Lese ich das richtig, dass es in Zukunft auch eine Farbänderung über RGB DPs geben wird?

> Alternative color-spaces not yet implemented:

    HUE_MILIGHT: number - Milight uses another starting-point in the hue color-cirlce:

    MilightHue = modulo(66 - (hue / 3.60), 100) * 2.55; 
    function modulo(n, m){ return ((n % m) + m) %m; }

    RGB_HUEONLY: string - instead of using HUE you can use the RGB_HUEONLY-Format (hex). In this special case the RGB-Format will only accept pure saturated colors of the hue-color-circle. Mixed white is not allowed
    RGB: string - instead of using HUE, SATURATION and COLOR_BRIGHTNESS you can use the RGB-Format (hex)
    RGBW: string - instead of using HUE, SATURATION, COLOR_BRIGHTNESS and WHITE_BRIGHTNESS you can use the RGBW-Format (hex)
    RGBWWCW: string - instead of HUE, SATURATION, COLOR_BRIGHTNESS, CT and WHITE_BRIGHTNESS you can use the RGBWWCW-Format (hex)

Wenn ja, wäre klasse, da ich einige Geräte habe, die kein HUE DP zur Farbänderung haben, oder es Probleme über den HUE DP bei der Änderung gibt.

**Comment by sbormann** [comment]
Ja, steht auf der toDo-Liste, wird aber leider noch etwas dauern. Bis dahin geht es am besten über ein Script zu lösen.
VG!

Von: ihavenonick <notifications@github.com>
Gesendet: Sonntag, 23. Juni 2019 11:46
An: sbormann/ioBroker.iqontrol <ioBroker.iqontrol@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [sbormann/ioBroker.iqontrol] RGB Steuerung geplant? (#53)


Lese ich das richtig, dass es in Zukunft auch eine Farbänderung über RGB DPs geben wird?

Alternative color-spaces not yet implemented:

HUE_MILIGHT: number - Milight uses another starting-point in the hue color-cirlce:







MilightHue = modulo(66 - (hue / 3.60), 100) * 2.55;



function modulo(n, m){ return ((n % m) + m) %m; }







RGB_HUEONLY: string - instead of using HUE you can use the RGB_HUEONLY-Format (hex). In this special case the RGB-Format will only accept pure saturated colors of the hue-color-circle. Mixed white is not allowed



RGB: string - instead of using HUE, SATURATION and COLOR_BRIGHTNESS you can use the RGB-Format (hex)



RGBW: string - instead of using HUE, SATURATION, COLOR_BRIGHTNESS and WHITE_BRIGHTNESS you can use the RGBW-Format (hex)



RGBWWCW: string - instead of HUE, SATURATION, COLOR_BRIGHTNESS, CT and WHITE_BRIGHTNESS you can use the RGBWWCW-Format (hex)



Wenn ja, wäre klasse, da ich einige Geräte habe, die kein HUE DP zur Farbänderung haben, oder es Probleme über den HUE DP bei der Änderung gibt.

**Comment by ihavenonick** [comment]
Keine Eile, hab den Adapter gestern erst entdeckt und bin recht begeistert davon.
